[check_socks]
check_urls = [
    "http://www.baidu.com",
    "http://www.google.com"
]
max_concurrent_req = 200
timeout = 5
retries = 2

[remote_urls]
urls = [
    "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt",
    "https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt",
    "https://raw.githubusercontent.com/r00tee/Proxy-List/main/Socks5.txt",
    "https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/generated/socks5_proxies.txt"
]
